# basic vars to make the templates cleaner
copyright: "Copyright {{ ansible_date_time.year }} Red Hat"
version_added: "1.0.0"

network_os: "{{ collection['name'] }}"

import_path: "ansible_collections.{{ collection['namespace'] }}.{{ collection['name'] }}.plugins.module_utils.network"
