- name: "Create the collection directory structure"
  ansible.builtin.file:
    path: "{{ collection['path'] }}/{{ item }}"
    state: directory
  with_items: "{{ directories }}"

- name: Touch the __init__.py in each directory
  ansible.builtin.copy:
    content: ""
    dest: "{{ collection['path'] }}/{{ item }}/__init__.py"
    force: no
  with_items: "{{ directories }}"

- name: Add license file to collection (Default is GPL-3.0)
  ansible.builtin.copy:
    src: "{{ license_file | default('gpl-3.0.txt') }}"
    dest: "{{ collection['path'] }}/LICENSE"

- name: Add README to collection
  ansible.builtin.template:
    src: "{{ item['source'] }}"
    dest: "{{ item['destination'] }}"
    force: no
  loop:
    - source: "README.md.j2"
      destination: "{{ collection['path'] }}/README.md"
    - source: "galaxy.yaml.j2"
      destination: "{{ collection['path'] }}/galaxy.yaml"
