- debug:
    msg: "Performing all common pre-tasks for scaffolding Network modules"

- name: Set/Reset directory paths
  set_fact:
    resource_module_directories:
      - modules
      - module_utils
      - module_utils/network
      - module_utils/network/{{ network_os }}
      - module_utils/network/{{ network_os }}/argspec
      - module_utils/network/{{ network_os }}/argspec/facts
      - module_utils/network/{{ network_os }}/argspec/{{ resource }}
      - module_utils/network/{{ network_os }}/config
      - module_utils/network/{{ network_os }}/config/{{ resource }}
      - module_utils/network/{{ network_os }}/facts
      - module_utils/network/{{ network_os }}/facts/{{ resource }}
      - module_utils/network/{{ network_os }}/utils
    rm_templates_dir: ['module_utils/network/{{ network_os }}/rm_templates']

- name: Add rm_templates dir when scaffolding module_network_cli
  set_fact:
    resource_module_directories: "{{ resource_module_directories + rm_templates_dir }}"
  when: plugin['type'] == 'module_network_cli'

- name: Copy argspec to a temporary file to format
  copy:
    # the prepended whitespace is needed to ensure that booleans are not lowercased
    content: " {{ (rm_documentation|ansible_network.cli_rm_builder.to_argspec)['argument_spec'] }}"
    dest: "{{ temp }}"
  changed_when: False

- name: Remove the whitespace from the argspec in temp file
  # the preceeding whitespace added in the previous task breaks `black`
  replace:
    path: "{{ temp }}"
    regexp: '^\s+'
    replace: ''
  changed_when: False

- name: Format dumped argspec using black with fixed line-length
  command: "black -l 79 {{ temp }}"
  changed_when: False

- name: Load formatted argspec and get other module kwargs
  set_fact:
    # this _has_ to be loaded as a string to preserve black formatting
    formatted_argspec: "{{ lookup('file', '{{ temp }}')|string() }}"

- name: Delete temp file
  file:
    path: "{{ temp }}"
    state: absent
  changed_when: False

- name: "Create the resource module directory structure"
  file:
    path: "{{ parent_directory }}/{{ item }}"
    state: directory
  with_items: "{{ resource_module_directories }}"

- name: Touch the __init__.py in each directory
  copy:
    content: ""
    dest: "{{ parent_directory }}/{{ item }}/__init__.py"
    force: no
  with_items: "{{ resource_module_directories }}"

- debug:
    msg: "Completed all common pre-tasks for scaffolding Network modules"
